### ISSUE TITLE
A small mistake on the README.md link 

### ISSUE THREAD

**Issue by 14H034160212** [FreedomIntelligence/ReasoningNLP#6]
Hi,

I am happy to see our PARARULE-Plus have been added in the README.md. Hopefully it can be added into the survey paper as well. I found there is a mistake that the paper and project links point to the PARARULE-Plus and ProofWriter are exact opposite. Can you correct that mistake? Thank you so much.

**Comment by OakYU** [comment]
Sorry for that mistake, I have corrected it.
